name: Node.js CI
on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '* * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Start
        run: | 
          npm install
          npm run start
