name: Node.js CI
on:
  push:
    branches: 
      - main
jobs:
  start:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: Start
        run: | 
          npm install
          npm run start
