name: Node.js CI
on:
  push:
    branches: 
      - main
  schedule:
    - cron:  '* * * * *'
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: Start
        run: | 
          npm install
          npm run start
